#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor eDP -d 1 2 3 4 5
# bspc monitor HDMI-A-0 -d 6 7 8 9 0
INTERNAL_MONITOR="eDP"
EXTERNAL_MONITOR="HDMI-A-0"
# on first load setup default workspaces
if [[ "$1" = 0 ]]; then
  if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
    bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
    bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
    bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
  else
    bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 10
  fi
fi

# determines thickness in pixels of border width of windows
bspc config border_width         2
# amounts of gaps in pixels around windows
bspc config window_gap          12

# ratio between two leaf nodes when split
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# mouse pointer can control which window gets focus
bspc config focus_follows_pointer true
# determines keyboard key to resize windows using the mouse
bspc config pointer_modifier super # mod1

# determines layout of the windows when split in automatic mode
bspc config automatic_scheme spiral

## Autostart
nitrogen --restore &
picom --config $HOME/.config/picom/picom.conf &
dunst &
polybar &

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Frame color in different states
bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

# space color when selecting new window position
bspc config presel_feedback_color "#595B82"

